server:
  port: 8090

resilience4j.circuitbreaker:
  instances:
    recommendations:
      registerHealthIndicator: true
      slidingWindowType: count_based
      slidingWindowSize: 10
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 5s
      failureRateThreshold: 30
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: true